### ISSUE TITLE
Node commands not working?

### ISSUE THREAD

**Issue by kpgarrod** [johnhidey/hdy.brackets-shell#22]
I have just installed the extension (Mac OSX 10.9) and can run normal shell commands (ls, pwd), but not node commands (bower install, npm install). I get 'command not found'. Clearly the path to 'bower' and 'npm' is not in $PATH, but I am not able to change the $PATH using export or by editing the bash profile. Any suggestions?

**Comment by carlosrubio** [comment]
I just installed the addon and found this issue. It is still broken? Can I help in any way?
