### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by mrmckeb** [johnhidey/hdy.brackets-shell#45]
Hi there,

This works quite well, but is a little hard to read when using the dark Brackets theme. The grey text blends into the background color.

**Comment by sika78** [comment]
Hi,
I'm having the same issue. Could you, please, add an option to switch white/dark background?

**Comment by johnhidey** [comment]
Have a look at the readme file.  It explains what settings need to be set in order to support the dark theme.  

Brackets-Shell adds the following options to your brackets.json 
* hdy.brackets-shell.dark: set to true if you are using Bracket's dark theme (defaults to false)

**Comment by sika78** [comment]
I did try this before but somehow it didn't worked. I try it again now & bazinga it worked.
Thanks John!
