### ISSUE TITLE
Some colors conflicting with brackets theme

### ISSUE THREAD

**Issue by danielmedina** [johnhidey/hdy.brackets-shell#48]
Some informations like browser and operating system are using a kind of grey that is difficult to see when using brackets dark theme.

**Comment by globexdesigns** [comment]
+1

**Comment by johnhidey** [comment]
@danielmedina and @globexdesigns have you both tried changing the app setting for dark themes?

`hdy.brackets-shell.dark`: set to true if you are using Bracket's dark theme (defaults to false)

**Comment by danielmedina** [comment]
aparently its ok. but it could be more easy to find. :)

**Comment by globexdesigns** [comment]
Aha! That did it. Thanks!

**Comment by Elliott-M** [comment]
What am I missing?  I can not figure it out to save my life.

**Comment by globexdesigns** [comment]
@Elliott-M In Brackets, to go Debug > Show Preference File. In the file that open up, scroll until you see:
```
hdy.brackets-shell.dark: false
```
And change it to:
```hdy.brackets-shell.dark: true```

**Comment by Elliott-M** [comment]
Thanks.
